spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    com.shell845.myblog: debug
  file:
    name: log/blog-dev.log
server:
  port: 8080